# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'SurfingAsUser' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'surfingAsUser' do
    @driver.get('http://localhost:3000/users/sign_in')
    @driver.manage.window.resize_to(1920,1004)
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('nikita.markov@nextmail.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('Nikita!8')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, '.button_to:nth-child(1) > .rightsidebarlinks').click
    @driver.find_element(:id, 'cpu').click
    dropdown = @driver.find_element(:id, 'cpu')
    dropdown.find_element(:xpath, "//option[. = 'Intel Core i7-13700K (LGA 1700, 253 W)']").click
    @driver.find_element(:css, '#cpu > option:nth-child(4)').click
    @driver.find_element(:id, 'gpu').click
    dropdown = @driver.find_element(:id, 'gpu')
    dropdown.find_element(:xpath, "//option[. = 'NVIDIA GeForce RTX 3070']").click
    @driver.find_element(:css, '#gpu > option:nth-child(5)').click
    @driver.find_element(:id, 'motherboard').click
    dropdown = @driver.find_element(:id, 'motherboard')
    dropdown.find_element(:xpath, "//option[. = 'ASUS ROG STRIX Z690-E GAMING WIFI (LGA 1700, 4 slots)']").click
    @driver.find_element(:css, '#motherboard > option:nth-child(4)').click
    @driver.find_element(:id, 'psu').click
    dropdown = @driver.find_element(:id, 'psu')
    dropdown.find_element(:xpath, "//option[. = '1200 W, 80 PLUS Platinum']").click
    @driver.find_element(:css, '#psu > option:nth-child(4)').click
    @driver.find_element(:id, 'disk').click
    dropdown = @driver.find_element(:id, 'disk')
    dropdown.find_element(:xpath, "//option[. = 'HDD, 14 TB']").click
    @driver.find_element(:css, '#disk > option:nth-child(9)').click
    @driver.find_element(:id, 'cooler').click
    dropdown = @driver.find_element(:id, 'cooler')
    dropdown.find_element(:xpath, "//option[. = 'LGA 1700, 250 W']").click
    @driver.find_element(:css, '#cooler > option:nth-child(2)').click
    @driver.find_element(:id, 'memory').click
    dropdown = @driver.find_element(:id, 'memory')
    dropdown.find_element(:xpath, "//option[. = '32 GB, 2400 MHz']").click
    @driver.find_element(:css, '#memory > option:nth-child(6)').click
    @driver.find_element(:name, 'commit').click
    cpu = @driver.find_element(:css, 'tr:nth-child(1) > td:nth-child(1)').text
    expect(cpu).to eq("Intel Core i7-13700K")
    gpu = @driver.find_element(:css, 'tr:nth-child(1) > td:nth-child(2)').text
    expect(gpu).to eq("NVIDIA GeForce RTX 3070")
    @driver.find_element(:css, 'td:nth-child(10) button').click
    @driver.find_element(:css, '.rightsidebarlinks').click
    @driver.find_element(:css, 'td:nth-child(11) button').click
    @driver.find_element(:css, '.button_to:nth-child(1) > .rightsidebarlinks').click
    @driver.find_element(:css, '.localebutton:nth-child(2)').click
    @driver.find_element(:css, '.button_to:nth-child(1) > .rightsidebarlinks').click
    @driver.find_element(:id, 'cpu').click
    dropdown = @driver.find_element(:id, 'cpu')
    dropdown.find_element(:xpath, "//option[. = 'Intel Core i7-12700K (LGA 1700, 190 Вт)']").click
    @driver.find_element(:css, '#cpu > option:nth-child(5)').click
    @driver.find_element(:id, 'gpu').click
    dropdown = @driver.find_element(:id, 'gpu')
    dropdown.find_element(:xpath, "//option[. = 'NVIDIA GeForce RTX 3070']").click
    @driver.find_element(:css, '#gpu > option:nth-child(5)').click
    dropdown = @driver.find_element(:id, 'motherboard')
    dropdown.find_element(:xpath, "//option[. = 'MSI MPG Z690 CARBON WIFI (LGA 1700, 4 слота)']").click
    @driver.find_element(:css, '#motherboard > option:nth-child(6)').click
    @driver.find_element(:id, 'psu').click
    dropdown = @driver.find_element(:id, 'psu')
    dropdown.find_element(:xpath, "//option[. = '1200 Вт, 80 PLUS Platinum']").click
    @driver.find_element(:css, '#psu > option:nth-child(4)').click
    @driver.find_element(:id, 'disk').click
    dropdown = @driver.find_element(:id, 'disk')
    dropdown.find_element(:xpath, "//option[. = 'HDD, 4 ТБ']").click
    @driver.find_element(:css, '#disk > option:nth-child(14)').click
    @driver.find_element(:id, 'cooler').click
    dropdown = @driver.find_element(:id, 'cooler')
    dropdown.find_element(:xpath, "//option[. = 'LGA 1700, 220 Вт']").click
    @driver.find_element(:css, '#cooler > option:nth-child(3)').click
    @driver.find_element(:id, 'memory').click
    dropdown = @driver.find_element(:id, 'memory')
    dropdown.find_element(:xpath, "//option[. = '8 ГБ, 3600 МГц']").click
    @driver.find_element(:css, '#memory > option:nth-child(12)').click
    @driver.find_element(:id, 'memory_number').click
    @driver.find_element(:css, '.content').click
    @driver.find_element(:name, 'commit').click
    cpu = @driver.find_element(:css, 'tr:nth-child(1) > td:nth-child(1)').text
    expect(cpu).to eq("Intel Core i7-12700K")
    gpu = @driver.find_element(:css, 'tr:nth-child(1) > td:nth-child(2)').text
    expect(gpu).to eq("NVIDIA GeForce RTX 3070")
    @driver.find_element(:css, 'td:nth-child(10) button').click
    @driver.find_element(:css, '.rightsidebarlinks').click
    @driver.find_element(:css, 'td:nth-child(11) button').click
    @driver.find_element(:css, '.button_to:nth-child(1) > .rightsidebarlinks').click
    @driver.find_element(:id, 'signoutbut').click
  end
end
